#为环境定义名称
server:
  port: 8080


dishmenu:
  fileUploadDir: D:/temp/
  fileDownloadDir: D:/temp/download/
  fileUploadToken: RWxJrjJkipZFu6LZZC3vKCloytNAFifuK17ouvSZnZKpRyGcvRWF7EQt9achTWl8xGoE4YHvc2IH8Efar4ZJREzqKi4amVumET3OUChFqulKvw8CZN36V75khda3kd97
  maxDishItem: 300

mail:
  hostname:mailer@mail.com
  port:9000
  from:mailer@mail.com