#为环境定义名称
spring:
  server:
    port: 8080





dishmenu:
  fileUploadDir: D:/temp/
  fileDownloadDir: D:/temp/download/
  fileUploadToken: RWxJrjJkipZFu6LZZC3vKCloytNAFifuK17ouvSZnZKpRyGcvRWF7EQt9achTWl8xGoE4YHvc2IH8Efar4ZJREzqKi4amVumET3OUChFqulKvw8CZN36V75khda3kd97
  maxDishItem: 300

servlet:
  multipart:   ## 修改文件上传的大小限制
    max-request-size: 1024MB   # 运行请求传递文件大小最大为1024MB
    max-file-size: 1024MB       # 运行服务器可以处理的最大文件大小1024MB
